language: r
cache: packages

warnings_are_errors: true

sudo: false

notifications:
  email:
    on_success: change
    on_failure: always

osx_image: xcode7

os:
  - linux
  - osx

r_packages:
  - covr
  
after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual
